version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: inventory-mysql
    restart: always
    env_file: secrets.env
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: inventory-app
    depends_on:
      - db
    ports:
      - "5000:5000"
    env_file: secrets.env

volumes:
  db_data:
